// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/verify-legacy': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/verify-legacy.post').default>>>>
    }
    '/api/n8n/toggle-workflow': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/n8n/toggle-workflow.post').default>>>>
    }
    '/api/users/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/create.post').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}