-- COPIA Y PEGA ESTO EN EL EDITOR SQL DE SUPABASE

/* =========================================
   1. HEALUP (Contexto Médico)
   ========================================= */

-- 1.1 Procedimientos Healup
create table if not exists public.healup_procedures (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  color text,
  price numeric default 0,
  discount numeric default 0
);

-- 1.2 Eventos Calendario Healup
create table if not exists public.healup_calendar_events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date text not null,
  time text not null,
  subject text not null,
  description text,
  procedure_id bigint, 
  client_name text,
  client_surname text,
  client_dni text,
  event_reason text
);

-- 1.3 Historial Médico Healup
create table if not exists public.healup_medical_history (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  surname text not null,
  dni text not null,
  phone text,
  email text,
  date_added text,
  attachment_name text,
  attachment_data text
);


/* =========================================
   2. BRADA PERFUMES (Contexto Ventas/Clientes)
   ========================================= */

-- 2.1 Procedimientos/Servicios Brada (Ej. Consultas, Entregas, etc.)
create table if not exists public.brada_procedures (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  color text,
  price numeric default 0,
  discount numeric default 0
);

-- 2.2 Eventos Calendario Brada
create table if not exists public.brada_calendar_events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date text not null,
  time text not null,
  subject text not null,
  description text,
  procedure_id bigint,
  client_name text,
  client_surname text,
  client_dni text,
  event_reason text
);

-- 2.3 Historial de Clientes Brada (Archivos, Recibos, etc.)
create table if not exists public.brada_client_history (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  surname text not null,
  dni text not null,
  phone text,
  email text,
  date_added text,
  attachment_name text,
  attachment_data text
);


/* =========================================
   3. ALEF COMPANY (Contexto Corporativo)
   ========================================= */

-- 3.1 Procedimientos/Servicios Alef
create table if not exists public.alef_procedures (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  color text,
  price numeric default 0,
  discount numeric default 0
);

-- 3.2 Eventos Calendario Alef
create table if not exists public.alef_calendar_events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date text not null,
  time text not null,
  subject text not null,
  description text,
  procedure_id bigint,
  client_name text,
  client_surname text,
  client_dni text,
  event_reason text
);

-- 3.3 Historial/Archivos Alef
create table if not exists public.alef_client_history (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  surname text not null,
  dni text not null,
  phone text,
  email text,
  date_added text,
  attachment_name text,
  attachment_data text
);


/* =========================================
   POLÍTICAS DE SEGURIDAD (RLS)
   ========================================= */

-- Habilitar RLS en todas las tablas
alter table public.healup_procedures enable row level security;
alter table public.healup_calendar_events enable row level security;
alter table public.healup_medical_history enable row level security;

alter table public.brada_procedures enable row level security;
alter table public.brada_calendar_events enable row level security;
alter table public.brada_client_history enable row level security;

alter table public.alef_procedures enable row level security;
alter table public.alef_calendar_events enable row level security;
alter table public.alef_client_history enable row level security;

-- Crear políticas permisivas (Permitir todo a todos los usuarios autenticados/anonimos por ahora para evitar bloqueos)
-- NOTA: En producción, deberías restringir esto por ID de usuario o rol.
create policy "Enable all access for Healup" on public.healup_procedures for all using (true);
create policy "Enable all access for Healup Events" on public.healup_calendar_events for all using (true);
create policy "Enable all access for Healup History" on public.healup_medical_history for all using (true);

create policy "Enable all access for Brada" on public.brada_procedures for all using (true);
create policy "Enable all access for Brada Events" on public.brada_calendar_events for all using (true);
create policy "Enable all access for Brada History" on public.brada_client_history for all using (true);

create policy "Enable all access for Alef" on public.alef_procedures for all using (true);
create policy "Enable all access for Alef Events" on public.alef_calendar_events for all using (true);
create policy "Enable all access for Alef History" on public.alef_client_history for all using (true);
